version: '3'
services:
  git-size:
    image: farshadnikfetrat/gitrepo-size-exporter:latest
    container_name: gitrepo-size-exp
    ports:
      - "9100:9100"
    environment:
      - GITLAB_ACCESS_TOKEN=XXX5
      - GITLAB_URL=https://gitlab.example.com
    restart: unless-stopped
